versions:
  "2024.1.1":
    folder: "all"
  "2024.1":
    folder: "all"
  "2024.0.4":
    folder: "all"
  "2024.0.2":
    folder: "all"
  "2024.0.1":
    folder: "all"
  "2023.1.4":
    folder: "all"
  "2023.1.3":
    folder: "all"
  "2023.1.2":
    folder: "all"
  "2023.1":
    folder: "all"
  "2023.0.6":
    folder: "all"
  "2023.0.4":
    folder: "all"
  "2023.0.2":
    folder: "all"
  "2023":
    folder: "all"
  "2022.1.7":
    folder: "all"
  "2022.1.6":
    folder: "all"
  "2022.1.4":
    folder: "all"
  "2022.1.1":
    folder: "all"
  "2022.1":
    folder: "all"
  "2022.0.1":
    folder: "all"
  "2022":
    folder: "all"
  "2021.1.4":
    folder: "all"
  "2021.1.2":
    folder: "all"
  "2021.1.1":
    folder: "all"
  "2021.1":
    folder: "all"
  "2021.0.4":
    folder: "all"
  "2021.0.2":
    folder: "all"
  "2021.0.1":
    folder: "all"
  "2021":
    folder: "all"
  "2020.1.2":
    folder: "all"
  "2020.1.1":
    folder: "all"
  "2020.1":
    folder: "all"
  "2020.0.2":
    folder: "all"
  "2020.0.1":
    folder: "all"
  "2020":
    folder: "all"
  "2019.2":
    folder: "all"
  "2019.1.4":
    folder: "all"
  "2019.1.1":
    folder: "all"
  "2019.1":
    folder: "all"
  "2019":
    folder: "all"
  "2018.1.2":
    folder: "all"
  "2018.1.1":
    folder: "all"
  "2018.1":
    folder: "all"